fix: added database parameter to connStr
shiblon/entroq pull request #42
Opened 2023-03-12 22:24 UTC by zahmadsaleem

By default `options.db` is ignored!
Therefore, when I pass the option `WithDB("xxx")` it is ignored.

I've added `"database=" + options.db` to be always passed on to connStr

2023-03-13 14:20 UTC, shiblon requested changes
Thanks for catching this!

I think we just need to wrap the database name in an escape function, e.g., `escp(options.db)` to make it safe.

2023-03-13 20:05 UTC, shiblon approved these changes
Thanks again for sending in this fix. Much appreciated.

2023-03-13 20:05 UTC, merged

2023-03-13 21:07 UTC, zahmadsaleem commented
You're welcome.
Thank you for your work!! loved the article as well :)

2023-03-17 17:56 UTC, shiblon commented
My pleasure!

Incidentally, have you tried the WAL implementation (in-memory, with write-ahead log and snapshots) instead of the PG backend? I'm curious to hear why folks choose one over the other.

2023-03-17 18:54 UTC, deardooley commented
FWIW, when queue size grows into the 10k range, we see response time on entroq start to noticeably slow down using a pg backend. With the WAL backend, performance stayed more consistent, but memory exploded. That’s likely due to message size, but it was something to consider as we look at deployment patterns.

—
Rion

On Mar 17, 2023, at 12:56 PM, Chris Monson ***@***.******@***.***>> wrote:



My pleasure!

Incidentally, have you tried the WAL implementation (in-memory, with write-ahead log and snapshots) instead of the PG backend? I'm curious to hear why folks choose one over the other.

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fshiblon%2Fentroq%2Fpull%2F42%23issuecomment-1474206836&data=05%7C01%7C%7Cb6ae40b2ac6246b494d708db2710ea05%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638146725819183087%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PQ9LN3h8sMnJ%2BDOnsvnGFRmbGoQ4hog4nasOqtTOz0Y%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAF7WMWTTVZGOIH7OIY7SDLW4SQUHANCNFSM6AAAAAAVYL3IMU&data=05%7C01%7C%7Cb6ae40b2ac6246b494d708db2710ea05%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638146725819183087%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=A0cCnLke2jrMojtQ3BWz5C%2BcWTrf8tAoV3YHfQnEK6Q%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2023-03-17 20:57 UTC, shiblon commented
@deardooley that makes sense to me for the in-memory implementation, and is by design.

What makes a little less sense is the PG performance degradation at such a small record count. I have seen that with PG before, though, and am just terrible at tuning that database, though I know some are able to extract much better performance out of it. I wonder if it's just a tuning issue there?

I would expect to see more consistent, but slower performance on well-tuned PG, and very memory-dependent performance on the WAL implementation.

Also, task sizes are generally best when they are small across all implementations. If something is pushing megabytes, it probably ought to be a file path instead of inlined bytes (generally true for systems like these, really). I would put the sweet spot at 10s of KB for task size, after that it starts getting dicey as you scale up.

2023-03-18 10:16 UTC, deardooley commented
Agreed on task size in the MB. My experience was with task size in the 1-2KB range. Task count was 30-50k per queue, with half a dozen queues. Maybe the solution is just to provide some tuned PG db configs that works well for different target message and queue sizes. I can contribute a helm chart and compose file to start from if there is interest.

—
Rion

On Mar 17, 2023, at 3:57 PM, Chris Monson ***@***.******@***.***>> wrote:



@deardooley<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdeardooley&data=05%7C01%7C%7Cbefc7ad47ba54f7884d808db272a2ef0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638146834344222305%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MZtOPivlp8OJGW8VW1KaaGd0M4zvOphBUairyRPQizQ%3D&reserved=0> that makes sense to me for the in-memory implementation, and is by design.

What makes a little less sense is the PG performance degradation at such a small record count. I have seen that with PG before, though, and am just terrible at tuning that database, though I know some are able to extract much better performance out of it. I wonder if it's just a tuning issue there?

I would expect to see more consistent, but slower performance on well-tuned PG, and very memory-dependent performance on the WAL implementation.

Also, task sizes are generally best when they are small across all implementations. If something is pushing megabytes, it probably ought to be a file path instead of inlined bytes (generally true for systems like these, really). I would put the sweet spot at 10s of KB for task size, after that it starts getting dicey as you scale up.

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fshiblon%2Fentroq%2Fpull%2F42%23issuecomment-1474395881&data=05%7C01%7C%7Cbefc7ad47ba54f7884d808db272a2ef0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638146834344378521%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AyXuEPkcoDPIAGTlPKQ1FvqrGHOrD1OXSkxm6MtFqx0%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAF7WMTJF3GFV4NVDQPFCYDW4TF2TANCNFSM6AAAAAAVYL3IMU&data=05%7C01%7C%7Cbefc7ad47ba54f7884d808db272a2ef0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638146834344378521%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eKs%2BWOXqv3edGKJISChN%2FXOOF6zkq4k6qrP0rmoB9I4%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-03-18 21:45 UTC, shiblon commented
Oh, interesting! That's a lot of tasks per queue, actually. It almost
sounds like it's being used for batch task storage instead of "nominally
communicating", which should be a valid thing to do with it, but it does
come with tradeoffs.

Often in systems like this, having that many tasks in a queue indicates a
backup in the system. I often use nominal queue size as a paging alert if
it gets above some reasonable number. Depends on the expected throughput,
of course.

A common design pattern when there is batch work to be done in the tens of
thousands of tasks is to store that work in sharded files, or just in a
plain database table, and then have a process that feeds it to the queue,
watching queue size. Completion of a task means pushing into another queue
where a worker picks it up, updates the database with all of the completion
information, and finally deletes the task.

YMMV in all things, but if you're interested in nerding out about queue
flow mechanisms, I'm here for you :)

On Sat, Mar 18, 2023 at 6:16 AM Rion Dooley ***@***.***>
wrote:

> Agreed on task size in the MB. My experience was with task size in the
> 1-2KB range. Task count was 30-50k per queue, with half a dozen queues.
> Maybe the solution is just to provide some tuned PG db configs that works
> well for different target message and queue sizes. I can contribute a helm
> chart and compose file to start from if there is interest.
>
> —
> Rion
>
> On Mar 17, 2023, at 3:57 PM, Chris Monson ***@***.******@***.***>> wrote:
>
>
>
> @deardooley<
> https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdeardooley&data=05%7C01%7C%7Cbefc7ad47ba54f7884d808db272a2ef0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638146834344222305%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MZtOPivlp8OJGW8VW1KaaGd0M4zvOphBUairyRPQizQ%3D&reserved=0>
> that makes sense to me for the in-memory implementation, and is by design.
>
> What makes a little less sense is the PG performance degradation at such a
> small record count. I have seen that with PG before, though, and am just
> terrible at tuning that database, though I know some are able to extract
> much better performance out of it. I wonder if it's just a tuning issue
> there?
>
> I would expect to see more consistent, but slower performance on
> well-tuned PG, and very memory-dependent performance on the WAL
> implementation.
>
> Also, task sizes are generally best when they are small across all
> implementations. If something is pushing megabytes, it probably ought to be
> a file path instead of inlined bytes (generally true for systems like
> these, really). I would put the sweet spot at 10s of KB for task size,
> after that it starts getting dicey as you scale up.
>
> —
> Reply to this email directly, view it on GitHub<
> https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fshiblon%2Fentroq%2Fpull%2F42%23issuecomment-1474395881&data=05%7C01%7C%7Cbefc7ad47ba54f7884d808db272a2ef0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638146834344378521%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AyXuEPkcoDPIAGTlPKQ1FvqrGHOrD1OXSkxm6MtFqx0%3D&reserved=0>,
> or unsubscribe<
> https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAF7WMTJF3GFV4NVDQPFCYDW4TF2TANCNFSM6AAAAAAVYL3IMU&data=05%7C01%7C%7Cbefc7ad47ba54f7884d808db272a2ef0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638146834344378521%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eKs%2BWOXqv3edGKJISChN%2FXOOF6zkq4k6qrP0rmoB9I4%3D&reserved=0>.
>
> You are receiving this because you were mentioned.Message ID: ***@***.***>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/shiblon/entroq/pull/42#issuecomment-1474804985>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAR4P4BLWA22GECGHQZ6CL3W4WDRLANCNFSM6AAAAAAVYL3IMU>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2023-03-18 21:46 UTC, shiblon commented
And yes, always interested in whatever real-world experience contributions
you might have! The more information the better, and helm charts for
tunings that work for given special workloads are always welcome.

On Sat, Mar 18, 2023 at 6:16 AM Rion Dooley ***@***.***>
wrote:

> Agreed on task size in the MB. My experience was with task size in the
> 1-2KB range. Task count was 30-50k per queue, with half a dozen queues.
> Maybe the solution is just to provide some tuned PG db configs that works
> well for different target message and queue sizes. I can contribute a helm
> chart and compose file to start from if there is interest.
>
> —
> Rion
>
> On Mar 17, 2023, at 3:57 PM, Chris Monson ***@***.******@***.***>> wrote:
>
>
>
> @deardooley<
> https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdeardooley&data=05%7C01%7C%7Cbefc7ad47ba54f7884d808db272a2ef0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638146834344222305%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MZtOPivlp8OJGW8VW1KaaGd0M4zvOphBUairyRPQizQ%3D&reserved=0>
> that makes sense to me for the in-memory implementation, and is by design.
>
> What makes a little less sense is the PG performance degradation at such a
> small record count. I have seen that with PG before, though, and am just
> terrible at tuning that database, though I know some are able to extract
> much better performance out of it. I wonder if it's just a tuning issue
> there?
>
> I would expect to see more consistent, but slower performance on
> well-tuned PG, and very memory-dependent performance on the WAL
> implementation.
>
> Also, task sizes are generally best when they are small across all
> implementations. If something is pushing megabytes, it probably ought to be
> a file path instead of inlined bytes (generally true for systems like
> these, really). I would put the sweet spot at 10s of KB for task size,
> after that it starts getting dicey as you scale up.
>
> —
> Reply to this email directly, view it on GitHub<
> https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fshiblon%2Fentroq%2Fpull%2F42%23issuecomment-1474395881&data=05%7C01%7C%7Cbefc7ad47ba54f7884d808db272a2ef0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638146834344378521%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AyXuEPkcoDPIAGTlPKQ1FvqrGHOrD1OXSkxm6MtFqx0%3D&reserved=0>,
> or unsubscribe<
> https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAF7WMTJF3GFV4NVDQPFCYDW4TF2TANCNFSM6AAAAAAVYL3IMU&data=05%7C01%7C%7Cbefc7ad47ba54f7884d808db272a2ef0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638146834344378521%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eKs%2BWOXqv3edGKJISChN%2FXOOF6zkq4k6qrP0rmoB9I4%3D&reserved=0>.
>
> You are receiving this because you were mentioned.Message ID: ***@***.***>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/shiblon/entroq/pull/42#issuecomment-1474804985>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAR4P4BLWA22GECGHQZ6CL3W4WDRLANCNFSM6AAAAAAVYL3IMU>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2023-03-23 09:12 UTC, zahmadsaleem commented
Hi @shiblon , could you release an new version ?

2023-03-23 09:16 UTC, zahmadsaleem commented
To answer your question

> Incidentally, have you tried the WAL implementation (in-memory, with write-ahead log and snapshots) instead of the PG backend? I'm curious to hear why folks choose one over the other.

I'm using entroq as a go package for now, and all my services would connect to pg and share the same queues. I assume I could achieve the same with WAL implementation and deploy entroq as a grpc server right?

2023-03-23 12:26 UTC, shiblon commented
You can still us the in-memory implementation if importing it as a package,
that should work fine. The whole thing is modular, just decide on your
"opener" being from the eqmem package when you create your instance, and
you're off and running.

On Thu, Mar 23, 2023 at 5:16 AM Ahmad Saleem ***@***.***>
wrote:

> To answer your question
>
> Incidentally, have you tried the WAL implementation (in-memory, with
> write-ahead log and snapshots) instead of the PG backend? I'm curious to
> hear why folks choose one over the other.
>
> I'm using entroq as a go package for now, and all my services would
> connect to pg and share the same queues. I assume I could achieve the same
> with WAL implementation and deploy entroq as a grpc server right?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/shiblon/entroq/pull/42#issuecomment-1480842886>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAR4P4F5TVM4ICNW4P54LRTW5QIG5ANCNFSM6AAAAAAVYL3IMU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>